MODEL:
  TYPE: anynet
  NUM_CLASSES: 10
ANYNET:
  STEM_TYPE: res_stem_cifar
  STEM_W: 16
  BLOCK_TYPE: res_basic_block_sm_dc_entire
  DEPTHS: [3, 3, 3]
  WIDTHS: [16, 32, 64]
  STRIDES: [1, 2, 2]
BN:
  USE_PRECISE_STATS: True
  NUM_SAMPLES_PRECISE: 1024
OPTIM:
  BASE_LR: 0.2
  LR_POLICY: cos
  MAX_EPOCH: 200
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0005
TRAIN:
  DATASET: cifar10
  SPLIT: train
  BATCH_SIZE: 256
  IM_SIZE: 32
  EVAL_PERIOD: 1
TEST:
  DATASET: cifar10
  SPLIT: test
  BATCH_SIZE: 200
  IM_SIZE: 32
NUM_GPUS: 2
DATA_LOADER:
  NUM_WORKERS: 4
OUT_DIR: .
