MODEL:
  TYPE: anymultinet
  NUM_CLASSES: 1000
ANYMULTINET:
  STEM_TYPE: res_stem_in
  BLOCK_TYPE: basic_res_bottleneck_block
  WIDTH_PER_GROUP: 64
  STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  DEPTHS: [3, 4, 6, 3]
  BETA_INV: 4
  FUSION_RATIO: 2
  V1: True
OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.075
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
TRAIN:
  DATASET: imagenet
  IM_SIZE: 224
  BATCH_SIZE: 96
TEST:
  DATASET: imagenet
  IM_SIZE: 256
  BATCH_SIZE: 60
DATA_LOADER:
  NUM_WORKERS: 4
NUM_GPUS: 3
OUT_DIR: .
